config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'buddies#index'
  resources :buddies do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :show, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end
  get 'my_listings', to: 'pages#my_listings'
  get 'my_bookings', to: 'pages#my_bookings'
  patch 'bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  patch 'bookings/:id/decline', to: 'bookings#decline', as: :decline_booking
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :cancel_booking

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :buddy
  has_many :reviews

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :name, :buddy_type, :skills, :description, :activities, :rate, :location, presence: true
  #length of description
  #collection of types to choose from?

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true
  validates :rating, inclusion: [1, 2, 3, 4, 5]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :buddies
  has_many :bookings, through: :buddies
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_buddy, only: [:new, :create]
  before_action :set_booking, only: [:accept, :decline, :cancel]

  def new
    @booking = Booking.new
  end

  def show
    set_booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.buddy = set_buddy
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking successfully updated'
    else
      render :edit
    end
  end

  def accept
    @booking.status = "Accepted"
    if @booking.save
      redirect_to my_listings_path
    else
      render :new
    end
  end

  def decline
    @booking.status = "Declined"
    if @booking.save
      redirect_to my_listings_path
    else
      render :new
    end
  end

  def cancel
    @booking.status = "Cancelled"
    if @booking.save
      redirect_back(fallback_location: root_path)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to root_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_buddy
    @buddy = Buddy.find(params[:buddy_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController

  def index
    if params[:query].present?
      sql_query = "buddy_type ILIKE :query OR activities ILIKE :query OR description ILIKE :query OR skills ILIKE :query"
      @buddies = Buddy.where(sql_query, query: "%#{params[:query]}%")
    else
      @buddies = Buddy.all
      @markers = @buddies.geocoded.map do |buddy|
        {
          lat: buddy.latitude,
          lng: buddy.longitude,
          info_window: render_to_string(partial: "info_window", locals: { buddy: buddy }),
          image_url: helpers.asset_url(buddy.url)
        }
      end
    end
  end

  def show
    @buddy = Buddy.find(params[:id])
    @marker = [{
        lat: @buddy.latitude,
        lng: @buddy.longitude,
        info_window: render_to_string(partial: "info_window", locals: { buddy: @buddy }),
        image_url: helpers.asset_url(@buddy.url)
      }]
  end

  def new
    @buddy = Buddy.new
  end

  def create
    @buddy = Buddy.new(buddy_params)
    @buddy.user = current_user
    if @buddy.save
      redirect_to buddy_path(@buddy)
    else
      render :new
    end
  end

  def edit
    @buddy = Buddy.find(params[:id])
  end

  def update
    @buddy = Buddy.find(params[:id])
    if @buddy.update(buddy_params)
      redirect_to @buddy, notice: 'Buddy successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @buddy = Buddy.find(params[:id])
    @buddy.destroy
    redirect_to buddies_path
  end

  private

  def buddy_params
    params.require(:buddy).permit(:name, :buddy_type, :skills, :description, :activities, :rate, :location, :url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def my_listings
    @user_buddies = current_user.buddies
    @bookings = current_user.bookings
  end

  def my_bookings
    @bookings = current_user.bookings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = set_booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="form">
  <h3>Edit booking for  <%= Buddy.find(@booking.buddy_id).name%> </h3>
    <%= simple_form_for [@buddy, @booking] do |f| %>
    <%= f.input :start_date, placeholder: 'Enter a start date' %>
    <%= f.input :end_date, placeholder: 'Enter a end date' %>
    <%= f.button :submit, :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="booking_page">
    <h1>add booking for  <%= @buddy.name %></h1>
    <br>
      <div class="form">
        <div class="form_wrapper">
          <div>
            <img src=<%= @buddy.url %>>
          </div>
          <div id='buddy-booking-dates' data-unavailable="<%= @buddy.unavailable_dates.to_json %>">
            <% if current_user.id != @buddy.user_id  %>
              <%= simple_form_for([@buddy, @booking]) do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker", id: 'booking_start_date'} %>
                <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker", id: 'booking_end_date'} %>
                <%= f.submit "Book", class: "btn btn-primary" %>
              <% end %>
                <%= link_to 'Back', buddy_path(@buddy), :class => "btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="d-flex">
    <div class="booking-details">
      <h1>Booking Details </h1>
      <h3>Buddy: <%= link_to @booking.buddy.name, buddy_path(@booking.buddy_id)%></h3>
      <h3>Booking start: <%= @booking.start_date %></h3>
      <h3>Booking end: <%= @booking.end_date %></h3>
      <h3>Cost: $<%= @booking.buddy.rate * (@booking.end_date - @booking.start_date).to_i %></h3>
      <% if @booking.status == "pending" %>
        <p> your booking is pending, awaiting <%= @booking.buddy.name %>'s approval</p>
      <% elsif @booking.status == "Accepted" %>
        <p> your booking has been accepted</p>
      <% else %>
        <p>your booking has been declined</p>
      <% end %>
      <%= link_to 'Edit Booking', edit_booking_path(@booking), :class => "btn btn-primary"%>
      <%= link_to "Back to Bookings", my_bookings_path, :class => "btn btn-primary" %>
    </div>
    <div class="buddy-reviews ms-5">
      <h2>Your review for this booking</h2>
      <% if @booking.reviews.present? %>
        <% @booking.reviews.each do |review|  %>
          <p><%= "⭐" * review.rating %></p>
          <% if review.comment.present? %>
          <p><%= review.comment %></p>
          <% else %>
            No comment for this review
          <% end %>
      <% end %>
      <% else  %>
        <p>You have not left a review</p>
        <%= link_to "Leave review", new_booking_review_path(@booking) , :class => "btn btn-primary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/buddies/_info_window.html.erb
<div class="mapboxgl-popup">
  <div class="mapboxgl-popup-content m-0 p-0">
  <img src= <%= buddy.url %> class="user-image card-img-top rounded-0">
    <div class="d-flex align-items-center justify-content-center p-1">
      <h3 class="m-0 p-2"><%= link_to buddy.name, buddy, :class => "stretched-link text-decoration-none" %></h3>
      <div class="popup-text">
      <p class="m-0"> <%= buddy.buddy_type %></p>
      <p class="m-0">$<%= buddy.rate %>/day</p>
      </div>
    </div>
  </div>
</div>

app/views/buddies/edit.html.erb
<div class="container">
  <div class="form">
    <%= simple_form_for @buddy do |f| %>
      <%= f.input :name  %>
      <%= f.input :buddy_type  %>
      <%= f.input :skills  %>
      <%= f.input :description %>
      <%= f.input :activities  %>
      <%= f.input :url  %>
      <%= f.input :location  %>
      <%= f.input :rate %>
      <%= f.button :submit, :class => "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back', buddy_path, :class => "btn btn-primary" %>
  </div>
</div>

app/views/buddies/index.html.erb
<div class="container">
  <h1>Buddies Near You</h1>
  <br>
  <div style="width: 100%; height: 300px; margin-bottom: 16px; border-radius: 10px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
<br>
  <h1>Our Most Popular buddies</h1>
  <br>
   <div class="cards">
    <% @buddies.each do |buddy| %>

  <div class="card bg-transparent border-0">

    <img src= <%= buddy.url %> class="buddy-img" alt="" width="300px;" height="300px;">

  <div class="card-body">
    <div class="card-text">
      <h2><%= link_to buddy.name, buddy, :class => "stretched-link" %></h2>
      <p> <%= buddy.buddy_type %></p>
      <p>$<%= buddy.rate %>/day</p>
    </div>
  </div>
</div>

<% end %>

</div>
</div>

app/views/buddies/new.html.erb
<div class="container">
  <h1>Time to list a new buddy</h1>
  <br>
  <br>
    <div class="form">
      <%= simple_form_for @buddy do |f| %>
      <div class="form_wrapper">
        <div class="form_div">
          <h3>The Basics:</h3>
          <%= f.input :name  %>
          <%= f.input :rate %>
          <%= f.input :location  %>
          <%= f.input :url,  label: "Link to profile picture" %>
          <%= f.input :buddy_type, label: "What kind of buddy are you?", :collection => %w[Dog Cat Human Object Other] %>
        </div>
        <div class="form_div">
          <h3>Why is your buddy is the best:</h3>
          <%= f.input :skills  %>
          <%= f.input :description %>
          <%= f.input :activities  %>
          <br>
          <br>
          <%= f.button :submit, :class => "btn btn-primary" %>
          <%= link_to 'Back', buddies_path, :class => "btn btn-info" %>
        </div>
            <div class="pic_of_doggo">
      <%= image_tag "Doggo.png" %>
    </div>
      </div>
      <% end %>


  </div>
</div>
<br>

app/views/buddies/show.html.erb
<div class="buddy_banner">
  <div class="container">
    <div class="image_and_text">
      <div class="section">
        <img src=<%= @buddy.url %>>
      </div>
      <div class="section">
          <h1>Hello! My name is <%= @buddy.name %></h1>
          <h2>I'm so excited to be your new best buddy!</h2>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="d-flex justify-content-between">
    <div class="buddy-info">
      <p><strong>Buddy Type: </strong><%= @buddy.buddy_type %><p>
      <p><strong>Skills: </strong><%= @buddy.skills %><p>
      <p><strong>Description: </strong><%= @buddy.description %><p>
      <p><strong>Activities: </strong><%= @buddy.activities %><p>
      <p><strong>Rate: </strong>$<%= @buddy.rate %> /per day<p>
      <div class="buddy-buttons">
        <%= link_to 'Book me', new_buddy_booking_path(@buddy), :class => "btn btn-primary" %>
        <%= link_to 'Edit Buddy', edit_buddy_path, :class => "btn btn-info" %>
        <%= link_to 'Delete', buddy_path(@buddy), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn btn-info"  %>
      </div>

    </div>
    <div style="width: 70%; height: auto; border-radius: 10px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @marker.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>
<br>
<div class="container">
  <div class="d-flex ">
    <div class="buddy-bookings me-5">
      <h2> <%= @buddy.name.capitalize %>'s booking history! </h2>
      <p> <%= @buddy.name.capitalize %> also has
      <% counter = 0 %>
      <% @buddy.bookings.each do |booking| %>
      <% booking.status == "pending" ? counter =+ 1 : counter %>
      <% end %>
      <strong> <%= counter %> </strong>
      pending requests! </p>
      <% @buddy.bookings.each do |booking|%>
      <% if booking.status == "Accepted" %>
      <p> <strong><%= link_to "Booking Duration:", booking %> </strong>
            <strong>Start date: </strong> <%= booking.start_date %>
            <strong>End date: </strong> <%= booking.start_date %> </p>
        <%end%>
      <% end %>
    </div>
    <div class="buddy-reviews ms-5">
      <h2>Reviews for <%= @buddy.name.capitalize %></h2>
      <% if @buddy.reviews.present? %>
        <% @buddy.reviews.each do |review|  %>
          <p><%= "⭐" * review.rating %></p>
          <% if review.comment.present? %>
          <p><%= review.comment %></p>
          <% else %>
            No comment for this review
          <% end %>
      <% end %>
      <% else  %>
        <p>There are no reviews for this buddy.</p>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>airbud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>

</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<p>These are all the buddies you have listed!</p>
<div class="cards">
  <% @user_buddies.each do |user_buddy| %>
  <div class="card-buddy">
    <h2> Buddy Name: <%= link_to user_buddy.name, user_buddy %> </h2>
    <ul>
    <% Booking.where("buddy_id = ?", user_buddy.id).each do |booking|%>
    <li>
    <p> <strong>Booking Duration </strong> </p>
      <p> <strong>Start date: </strong> <%= booking.start_date %>
          <strong>End date: </strong> <%= booking.start_date %> </p>
      <br>
      <p>  <strong>status: </strong> <%= booking.status  %></p>
      <br>
      <%= link_to 'Accept?', accept_booking_path(booking), method: :patch, data: { confirm: "Are you sure?" }, :class => "btn btn-primary" %>
      <%= link_to 'Decline?', decline_booking_path(booking), method: :patch, data: { confirm: "Are you sure?" }, :class => "btn btn-info" %>
    </li>
    <% end %>
    </ul>
  </div>
  <% end %>
</div>
<br>
<%= link_to 'New Buddy', new_buddy_path, :class => "btn btn-primary" %>
<%= link_to 'Index/Home', buddies_path, :class => "btn btn-primary" %>

app/views/pages/home.html.erb
<div class="container justify-content-center">
<h1>airbud</h1>
<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/pages/my_bookings.html.erb
 <div class="my-bookings">
  <h1>My Bookings</h1>
  <p>These are all the buddies you have booked!</p>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="Pending-tab" data-bs-toggle="tab" data-bs-target="#Pending" type="button" role="tab" aria-controls="Pending" aria-selected="true"><strong>Pending</strong></button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="Accepted-tab" data-bs-toggle="tab" data-bs-target="#Accepted" type="button" role="tab" aria-controls="Accepted" aria-selected="false"><strong>Accepted</strong></button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="Declined-tab" data-bs-toggle="tab" data-bs-target="#Declined" type="button" role="tab" aria-controls="Declined" aria-selected="false"><strong>Declined</strong></button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="Cancelled-tab" data-bs-toggle="tab" data-bs-target="#Cancelled" type="button" role="tab" aria-controls="Cancelled" aria-selected="false"><strong>Cancelled</strong></button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="Pending" role="tabpanel" aria-labelledby="Pending-tab">
          <% @bookings.each do |booking| %>
            <% if booking.status == 'pending'%>
              <div class="card bg-transparent border-0 my-4" style="max-width: 700px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src= <%= Buddy.find(booking.buddy_id).url %> class="buddy-img img-fluid rounded-start" alt="" style="width: 250px; height: 200px;">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <div class="card-text">
                        <h2> <%= link_to Buddy.find(booking.buddy_id).name, booking, :class => "stretched-link" %> </h2>
                        <p> <strong>Start date: </strong> <%= booking.start_date %> </p>
                        <p> <strong>End date: </strong> <%= booking.start_date %> </p>
                        <p>  <strong>Status: </strong> <%= booking.status  %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
      </div>
      <div class="tab-pane fade" id="Accepted" role="tabpanel" aria-labelledby="Accepted-tab">
        <% @bookings.each do |booking| %>
            <% if booking.status == 'Accepted'%>
              <div class="d-flex">
                <div class="card bg-transparent border-0 my-4" style="width: 700px;">
                  <div class="row g-0">
                    <div class="col-md-4">
                      <img src= <%= Buddy.find(booking.buddy_id).url %> class="buddy-img img-fluid rounded-start" alt="" style="width: 100%; height: 200px;">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body ">
                        <div class="card-text">
                          <h2> <%= link_to Buddy.find(booking.buddy_id).name, booking, :class => "stretched-link"%> </h2>
                          <p> <strong>Start date: </strong> <%= booking.start_date %> </p>
                          <p> <strong>End date: </strong> <%= booking.start_date %> </p>
                          <p>  <strong>Status: </strong> <%= booking.status  %></p>
                          <%= link_to 'Cancel?', cancel_booking_path(booking), method: :patch, data: { confirm: "Are you sure?" }, :class => "btn btn-info text-white position-absolute" %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="align-self-center">

                </div>
              </div>
            <% end %>
          <% end %>
      </div>
      <div class="tab-pane fade" id="Declined" role="tabpanel" aria-labelledby="Declined-tab">
        <% @bookings.each do |booking| %>
            <% if booking.status == 'Declined'%>
              <div class="card bg-transparent border-0 my-4" style="max-width: 700px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src= <%= Buddy.find(booking.buddy_id).url %> class="buddy-img img-fluid rounded-start" alt="" style="width: 250px; height: 200px;">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <div class="card-text">
                        <h2> <%= link_to Buddy.find(booking.buddy_id).name, booking, :class => "stretched-link" %> </h2>
                        <p> <strong>Start date: </strong> <%= booking.start_date %> </p>
                        <p> <strong>End date: </strong> <%= booking.start_date %> </p>
                        <p>  <strong>Status: </strong> <%= booking.status  %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
      </div>
      <div class="tab-pane fade" id="Cancelled" role="tabpanel" aria-labelledby="Cancelled-tab">
        <% @bookings.each do |booking| %>
            <% if booking.status == 'Cancelled'%>
              <div class="card bg-transparent border-0 my-4" style="max-width: 700px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src= <%= Buddy.find(booking.buddy_id).url %> class="buddy-img img-fluid rounded-start" alt="" style="width: 250px; height: 200px;">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <div class="card-text">
                        <h2> <%= link_to Buddy.find(booking.buddy_id).name, booking, :class => "stretched-link" %> </h2>
                        <p> <strong>Start date: </strong> <%= booking.start_date %> </p>
                        <p> <strong>End date: </strong> <%= booking.start_date %> </p>
                        <p>  <strong>Status: </strong> <%= booking.status  %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
</div>

app/views/pages/my_listings.html.erb
<div class="container">
  <h1>My Listings</h1>
  <p>These are all the buddies you have listed!</p>

    <% @user_buddies.each do |user_buddy| %>
    <div class="card justify-content-start align-items-start bg-transparent border-0 my-4" >
      <div class="row g-0">
      <div class="col">
        <h2> <%= link_to user_buddy.name, user_buddy, :class => "text-decoration-none" %> </h2>
        <img src= <%= user_buddy.url %> class="buddy-img img-fluid rounded-start" alt="" style="width: 250px; height: 200px;">
      </div>
      <% user_buddy.bookings.each do |booking|%>
        <div class="col">
          <div class="card-body">
            <p> <strong>Booking: </strong> </p>
            <p> <strong>Start date: </strong> <%= booking.start_date %> </p>
            <p> <strong>End date: </strong> <%= booking.start_date %> </p>
            <p>  <strong>status: </strong> <%= booking.status  %></p>
            <% if booking.status == "pending" %>
            <%= link_to 'Accept?', accept_booking_path(booking), method: :patch, data: { confirm: "Are you sure?" }, :class => "btn btn-primary" %>
            <%= link_to 'Decline?', decline_booking_path(booking), method: :patch, data: { confirm: "Are you sure?" }, :class => "btn btn-info" %>
            <% elsif booking.status == "Accepted" %>
            <%= link_to 'Cancel?', cancel_booking_path(booking), method: :patch, data: { confirm: "Are you sure?" }, :class => "btn btn-info" %>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="px-3 border-bottom navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="logo_and_tag">
        <div class="logo">
          <%= image_tag "logo.png" %>
        </div>
        <div class="title_and_tag_line">
          <h1> airbud </h1>
          <p> Find the perfect buddy for you! </p>
        </div>
      </div>
    <% end %>

  <div class="d-flex justify-content-around">
    <div>
    <%= form_tag root_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a bud"
      %>
    </div>
    <div>
      <%= submit_tag "Search", class: "btn btn-primary rounded .ml-5" %>
      <% end %>
    </div>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List a Buddy", new_buddy_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Listings", my_listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", my_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "raggy.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>